### ISSUE TITLE
how to train the model on my own dataset

### ISSUE THREAD

**Issue by 980202006** [nii-yamagishilab/project-CURRENNT-public#7]
thank you for the code, can I train it on my own dataset?

**Comment by TonyWangX** [comment]
Hi, the scripts to use the code is available here: https://github.com/nii-yamagishilab/project-CURRENNT-scripts

There are examples to train networks on a tiny dataset. 

With those examples, I think you can easily figure out how to prepare the data and run the scripts

**Comment by 980202006** [comment]
thank you
