### ISSUE TITLE
How to use multi gpu?

### ISSUE THREAD

**Issue by hoyden** [nii-yamagishilab/project-CURRENNT-public#9]

**Comment by TonyWangX** [comment]
Sorry, I am afraid that there is no easy way for multi GPU (from my limited experience). 

CURRENNT mainly uses CUDA/THURST API https://docs.nvidia.com/cuda/thrust/index.html. 
Multi-GPU for CUDA/THRUST is beyond my knowledge.

**Comment by hoyden** [comment]
Thx for reply. It's OK! I will try it.
